# Generated by Django 3.1.7 on 2021-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
