# Generated by Django 3.1.6 on 2021-03-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0002_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
            ],
        ),
    ]
