# Generated by Django 3.1.7 on 2021-04-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0002_auto_20210413_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/exgame/images/default_image.png', null=True, upload_to='images/profile/'),
        ),
    ]
