# Generated by Django 3.1.7 on 2021-03-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0003_auto_20210330_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
