# Generated by Django 3.1.6 on 2021-03-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0003_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=1000)),
            ],
        ),
    ]
