# Generated by Django 3.1.6 on 2021-03-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0004_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post',
            new_name='post_text',
        ),
    ]
