# Generated by Django 3.1.7 on 2021-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0004_posts_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/eg/images/default_image.png', null=True, upload_to='images/profile/'),
        ),
    ]
