# Generated by Django 3.1.7 on 2021-04-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0005_auto_20210331_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
