# Generated by Django 3.1.7 on 2021-04-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eg', '0006_auto_20210401_0000'),
        ('eg', '0005_auto_20210331_1647'),
    ]

    operations = [
    ]
